---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Цена товара со скидкой не должна быть больше цены товара без скидки
  - Цены на товар должны быть больше 0
  - Пользователь не должен удалять, редактировать и добавлять новый товар в список товаров
  - Соблюдение нормативных и законодательных актов
  - При смене языка меняется весь текс
  - В карточке товара должна быть возможность просмотра дополнительных изображений товара
  - Пользователь должен иметь возможность сбросить выбранную категорию в фильтре
